/* Generated by AN DISI Unibo */ 
package it.unibo.boundaryqak30

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Boundaryqak30 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 var NumStep     = 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 NumStep     = 0;  
						updateResourceRep( "waitingOn( edge_$NumStep )"  
						)
					}
					 transition(edgeName="t00",targetState="coverNextEdge",cond=whenDispatch("init"))
				}	 
				state("coverNextEdge") { //this:State
					action { //it:State
						delay(500) 
						updateResourceRep( "doingastep $NumStep"  
						)
						request("step", "step(350)" ,"basicrobot" )  
					}
					 transition(edgeName="t01",targetState="coverNextEdge",cond=whenReply("stepdone"))
					transition(edgeName="t02",targetState="otherEdge",cond=whenReply("stepfail"))
					interrupthandle(edgeName="t03",targetState="handleStop",cond=whenDispatch("stop"),interruptedStateTransitions)
				}	 
				state("otherEdge") { //this:State
					action { //it:State
						 NumStep = NumStep + 1  
						println("otherEdge")
						updateResourceRep( "covering( edge_$NumStep)"  
						)
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
					}
					 transition( edgeName="goto",targetState="coverNextEdge", cond=doswitchGuarded({ NumStep < 4  
					}) )
					transition( edgeName="goto",targetState="endOfWork", cond=doswitchGuarded({! ( NumStep < 4  
					) }) )
				}	 
				state("handleStop") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep( "stopped"  
						)
					}
					 transition(edgeName="t04",targetState="exitFromStop",cond=whenDispatch("resume"))
				}	 
				state("exitFromStop") { //this:State
					action { //it:State
						updateResourceRep( "resumed"  
						)
						returnFromInterrupt(interruptedStateTransitions)
					}
				}	 
				state("endOfWork") { //this:State
					action { //it:State
						updateResourceRep( "athomeagain"  
						)
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
