/* Generated by AN DISI Unibo */ 
package it.unibo.robotappl1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robotappl1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "activate"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 val inmapname   = "map2019"  
			   var PathTodo    =  ""  
		return { //this:ActionBasciFsm
				state("activate") { //this:State
					action { //it:State
						unibo.kotlin.planner22Util.loadRoomMap( inmapname  )
						unibo.kotlin.planner22Util.initAI(  )
						unibo.kotlin.planner22Util.updateMap( "l", ""  )
						println("uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu")
						unibo.kotlin.planner22Util.showMap(  )
					}
				}	 
				state("work") { //this:State
					action { //it:State
						unibo.kotlin.planner22Util.setGoal( 5, 3  )
						 PathTodo = unibo.kotlin.planner22Util.doPlan().toString() 
								   //PathTodo = PathTodo.replace("[","").replace("]","").replace(", ",",")	
								   //PathTodo = PathTodo.replace(", ",",")
						println("Azioni pianificate: $PathTodo")
						request("dopath", "dopath($PathTodo,pathcaller)" ,"pathexec" )  
					}
					 transition(edgeName="t00",targetState="pathok",cond=whenReply("dopathdone"))
					transition(edgeName="t01",targetState="pathko",cond=whenReply("dopathfail"))
				}	 
				state("pathok") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
				}	 
				state("pathko") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						unibo.kotlin.planner22Util.showMap(  )
						unibo.kotlin.planner22Util.showCurrentRobotState(  )
					}
				}	 
				state("end") { //this:State
					action { //it:State
						println("BYE")
					}
				}	 
			}
		}
}
