/* Generated by AN DISI Unibo */ 
package it.unibo.applobserver

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Applobserver ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CoapObserverSupport(myself, "localhost","8032","ctxboundaryqak30","boundaryqak30")
					}
					 transition(edgeName="t07",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
					transition(edgeName="t08",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleUpdate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("coapUpdate(RESOURCE,VALUE)"), Term.createTerm("coapUpdate(RESOURCE,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 MsgUtil.outgreen("applobserver OBSERVES: ${payloadArg(1)} FROM ${payloadArg(0)} ")  
						}
					}
					 transition(edgeName="t09",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
					transition(edgeName="t010",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("alarm(X)"), Term.createTerm("alarm(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 MsgUtil.outmagenta("applobserver handles ALARM: ${payloadArg(0)}")  
						}
					}
					 transition(edgeName="t011",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
					transition(edgeName="t012",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
			}
		}
}
