/* Generated by AN DISI Unibo */ 
package it.unibo.corecaller1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Corecaller1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						request("cmd", "cmd(caller1)" ,"resourcecore" )  
					}
					 transition(edgeName="t00",targetState="handleReply",cond=whenReply("replytocmd"))
					transition(edgeName="t01",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleReply") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						delay(5000) 
						println("       --- caller1 handleReply: emit fire")
						emit("alarm", "alarm(fire)" ) 
					}
					 transition(edgeName="t02",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						println("       --- caller1 handleAlarm   ")
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t03",targetState="handleReply",cond=whenReply("replytocmd"))
					transition(edgeName="t04",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
			}
		}
}
