/* Generated by AN DISI Unibo */ 
package it.unibo.controller22

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Controller22 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 val DLIMIT = 30  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("${name} STARTS - Activates the sonar")
						forward("sonaractivate", "info(ok)" ,"sonar22" ) 
					}
					 transition(edgeName="t06",targetState="doBusinessWork",cond=whenEvent("sonardata"))
				}	 
				state("doBusinessWork") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(V)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var D = payloadArg(0).toInt()  
								forward("polar", "polar($D,90)" ,"radar22" ) 
								if(  D <= DLIMIT  
								 ){forward("ledCmd", "ledCmd(on)" ,"led22" ) 
								}
								else
								 {forward("ledCmd", "ledCmd(off)" ,"led22" ) 
								 }
						}
					}
					 transition(edgeName="t07",targetState="doBusinessWork",cond=whenEvent("sonardata"))
				}	 
			}
		}
}
