version: '3'
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi:2.0
    ## image: virtualrobotdisi:2.0
    ports:
      - 8090:8090
      - 8091:8091
  robot:
    image: docker.io/natbodocker/basicrobot21virtual:1.0
    ##image: basicrobot21virtual:1.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv

## -------------------------------------------------------------
## See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f basicrobotVirtual.yaml up
## docker-compose run --service-ports wenv
## docker-compose run --service-ports robot  ATTIVA ANCHE wenv