% ========================================================
%  Generated by oaW from the user model in DSL
% ========================================================  

% ---------------------------------------------- 
% Unit
% ---------------------------------------------- 
unit('Costruire sistemi software: dai modelli al codice').

% ---------------------------------------------- 
% Learning paths names
% ---------------------------------------------- 
indexName('index').

% --------------------------------------------- 
% Learning path content
% --------------------------------------------- 
index('index','introduzione','Introduzione','',unused).
index('index','crisiSoftware','La crisi del software','introduzione',unused).
index('index','dimAlgoritmica','La dimensione algoritmica','introduzione',unused).
index('index','dimSistemistica','La dimensione sistemistica','introduzione',unused).
index('index','ingSoftware','Ingegenria del software','introduzione',unused).
index('index','metodoMetodologia','Meetodo e metodologia','ingSoftware',unused).
index('index','storiaDelleMetodologie','Storia delle metodologie','ingSoftware',unused).
index('index','cmm','Capability Maturity Model','ingSoftware',unused).
index('index','processiSviluppoSoftware','Processi di produzione del software','',unused).
index('index','qualita','Qualita'?','processiSviluppoSoftware',unused).
index('index','processiACasscata','Processi a cascata','processiSviluppoSoftware',unused).
index('index','processiASpirale','Processi a spirale','processiSviluppoSoftware',unused).
index('index','processiBasatiSuModelli','Processi basati su modelli','processiSviluppoSoftware',unused).
index('index','processiAgili','Processi agili','processiSviluppoSoftware',unused).
index('index','xpPratiche','Pratiche dell'eXtreme Programming','processiAgili',unused).
index('index','qualeProcesso','Quale processo?','processiSviluppoSoftware',unused).
index('index','versoUnProcesso','Verso un processo di sviluppo','',unused).
index('index','paradigmi','Linguaggi e paradigmi computazionali','versoUnProcesso',unused).
index('index','sintassiSemantica','Sintassi e semantica','paradigmi',unused).
index('index','macchineBase','Macchine base','paradigmi',unused).
index('index','macchineAstratte','Macchine astratte','macchineBase',unused).
index('index','funzioniProcedure','Funzionai e procedure','paradigmi',unused).
index('index','moduliOggetti','Moduli','paradigmi',unused).
index('index','oggetti','Il paradigma ad oggetti','paradigmi',unused).
index('index','daOggettiAUML','Dagli oggetti a UML','paradigmi',unused).
index('index','componentiSoftware','Componenti Software','paradigmi',unused).
index('index','inversioneControllo','Inversione di controllo','componentiSoftware',unused).
index('index','paradigmaAgenti','Il paradigma ad agenti','paradigmi',unused).
index('index','agenti','Agenti','paradigmaAgenti',unused).
index('index','agentiVsOggetti','Agenti vs. oggetti','paradigmaAgenti',unused).
index('index','umlFirst','Il linguaggio UML','versoUnProcesso',unused).
index('index','concettoDiModello','Il concetto di modello','umlFirst',unused).
index('index','introUml','introUml','umlFirst',unused).
index('index','layerUml','layerUml','umlFirst',unused).
index('index','introMOF','introMOF','umlFirst',unused).
index('index','diagrammiAM','diagrammiAM','umlFirst',unused).
index('index','introUMLProfili','introUMLProfili','umlFirst',unused).
index('index','umlComeLinguaggio','coreUML','umlFirst',unused).
index('index','introUMLAction','introUMLAction','umlFirst',unused).
index('index','introOCL','introOCL','umlFirst',unused).
index('index','architettureSistemi','Architetture','versoUnProcesso',unused).
index('index','stileArchitetturale','Stile architetturale','architettureSistemi',unused).
index('index','mda','Architetture model driven','architettureSistemi',unused).
index('index','dimensioniSistemi','Dimensioni','versoUnProcesso',unused).
index('index','struttura','Struttura','dimensioniSistemi',unused).
index('index','strutturaIntro','strutturaIntro','struttura',unused).
index('index','classi','classi','strutturaIntro',unused).
index('index','package','package','strutturaIntro',unused).
index('index','strutComp','strutComp','strutturaIntro',unused).
index('index','componentiD','componentiD','strutturaIntro',unused).
index('index','deploymentD','deploymentD','strutturaIntro',unused).
index('index','interazione','Interazione','dimensioniSistemi',unused).
index('index','interazioneIntro','interazioneIntro','interazione',unused).
index('index','sequenzaIntro','sequenzaIntro','interazioneIntro',unused).
index('index','messaggio','Messaggio','sequenzaIntro',unused).
index('index','combinedfragment','combinedfragment','sequenzaIntro',unused).
index('index','esempiInterazione','esempiInterazione','sequenzaIntro',unused).
index('index','sincroni','sincroni','esempiInterazione',unused).
index('index','asincroni','asincroni','esempiInterazione',unused).
index('index','conclusioni','conclusioni','interazioneIntro',unused).
index('index','comportamento','Comportamento','dimensioniSistemi',unused).
index('index','comportamentoIntro','comportamentoIntro','comportamento',unused).
index('index','stato','stato','comportamentoIntro',unused).
index('index','attivita','attivita','comportamentoIntro',unused).
index('index','introPattern','I pattern','versoUnProcesso',unused).
index('index','ruoloPattern','Ruolo dei pattern','introPattern',unused).
index('index','insiemiDiPattern','Insisemi di pattern','introPattern',unused).
index('index','patternLanguages','Pattern languages','introPattern',unused).
index('index','piattaforme','Piattaforme operative model driven','versoUnProcesso',unused).
index('index','processoLogico','Percorso Logico','',unused).
index('index','impostazioneGenerale','Impostazione generale','processoLogico',unused).
index('index','sitoApplicazione','Workflow ed artefatti','processoLogico',unused).
index('index','workflowRequisiti','Analisi dei requisiti','processoLogico',unused).
index('index','ieeeRequisiti','Analisi dei requisiti','workflowRequisiti',unused).
index('index','analisiRequisiti','Analisi dei requisiti','workflowRequisiti',unused).
index('index','useCase','Analisi dei requisiti','analisiRequisiti',unused).
index('index','relazioniUsecases','Analisi dei requisiti','useCase',unused).
index('index','scenari','Analisi dei requisiti','useCase',unused).
index('index','requisitNonFunzionali','Analisi dei requisiti','workflowRequisiti',unused).
index('index','workflowAnalisi','Analisi workflow','processoLogico',unused).
index('index','analisiProblema','Analisi del problema','workflowAnalisi',unused).
index('index','architetturaLogica','Architettura logica','analisiProblema',unused).
index('index','schemiArchitettura','Schemi architetturali','architetturaLogica',unused).
index('index','layers','Layers','analisiProblema',unused).
index('index','analisiRischi','Analisi dei rischi','workflowAnalisi',unused).
index('index','pianoCollaudo','Piano di collaudo','processoLogico',unused).
index('index','pianoLavoro','Piano di lavoro','processoLogico',unused).
index('index','workflowProgetto','Progetto','processoLogico',unused).
index('index','progettazione','Progettazione','workflowProgetto',unused).
index('index','sviluppoBottomUp','Sviluppo borrom-up','workflowProgetto',unused).
index('index','piattaformeFramework','Piattaforme e framework','sviluppoBottomUp',unused).
index('index','applicationFramework','Application framework','sviluppoBottomUp',unused).
index('index','sviluppoTopDown','Sviluppo top-down','workflowProgetto',unused).
index('index','projectByPattern','Progetti basati su pattern','sviluppoTopDown',unused).
index('index','implementazione','Implementazione','processoLogico',unused).
index('index','workflowCollaudo','Analisi dei requisiti','processoLogico',unused).
index('index','deployment','Deployment','processoLogico',unused).
index('index','maintenance','Maintenance','processoLogico',unused).
index('index','esempioModelBased','Espressioni','',unused).
index('index','analisiRequisitiExp','Analisi dei requisiti','esempioModelBased',unused).
index('index','modelloDominioExp','modelloDominioExp','analisiRequisitiExp',unused).
index('index','modelloTokenExp','modelloTokenExp','modelloDominioExp',unused).
index('index','modelloExpExp','modelloExpExp','modelloDominioExp',unused).
index('index','pianoCollaudoExp','pianoCollaudoExp','analisiRequisitiExp',unused).
index('index','sintassiAstrattaExp','modelloDominioExp','analisiRequisitiExp',unused).
index('index','genCodeToolsExp','genCodeToolsExp','analisiRequisitiExp',unused).
index('index','analisiProblemaExp','analisiProblemaExp','esempioModelBased',unused).
index('index','archLogicaExp','archLogicaExp','analisiProblemaExp',unused).
index('index','archLogicaStruttura','archLogicaStruttura','archLogicaExp',unused).
index('index','archLogicaInterazione','archLogicaInterazione','archLogicaExp',unused).
index('index','archLogicaComportamento','archLogicaComportamento','archLogicaExp',unused).
index('index','comportamentoSistema','comportamentoSistema','archLogicaExp',unused).
index('index','pianoLavoroExp','pianoLavoroExp','esempioModelBased',unused).
index('index','progettoExp','progettoExp','esempioModelBased',unused).
index('index','inputDev08Project','inputDev08Project','progettoExp',unused).
index('index','lexer08Project','Progetto lexer','progettoExp',unused).
index('index','parser08Project','Progetto parser','progettoExp',unused).
index('index','evaluator08Project','evaluator08Project','progettoExp',unused).
index('index','implementazioneExp','implementazioneExp','esempioModelBased',unused).
index('index','inputDevImplementation','inputDevImplementation','implementazioneExp',unused).
index('index','lexer08Implementation','lexer08Implementation','implementazioneExp',unused).
index('index','parser08Implementation','parser08Implementation','implementazioneExp',unused).
index('index','evaluatorImplementation','evaluatorImplementation','implementazioneExp',unused).
index('index','sysExpImplementation','sysExpImplementation','implementazioneExp',unused).
index('index','introTecnologie','Tecnologie','',unused).
index('index','componenti','Componenti','introTecnologie',unused).
index('index','osgi','OSGi','componenti',unused).
index('index','bundle','Bundle','osgi',unused).
index('index','bundleDependency','bundleDependency','osgi',unused).
index('index','classLoading','classLoading','osgi',unused).
index('index','bundleLifeCycle','bundleLifeCycleOSGi','osgi',unused).
index('index','bundleObject','bundleObject','osgi',unused).
index('index','bundleContext','bundleContext','osgi',unused).
index('index','osgiServices','osgiServices','osgi',unused).
index('index','osgiServiceDependency','osgiServiceDependency','osgi',unused).
index('index','osgiServiceTracker','osgiServiceTracker','osgi',unused).
index('index','osgiServiceBinder','osgiServiceBinder','osgi',unused).
index('index','equinoxUsageTutorial','equinoxUsageTutorial','osgi',unused).
index('index','realizzareBundle','realizzareBundle','osgi',unused).
index('index','introMdsd','introMdsd','',unused).
index('index','introUml2','introUml2','introMdsd',unused).
index('index','razionaleMOF','razionaleMOF','introUml2',unused).
index('index','riusoInMOF','riusoInMOF','introUml2',unused).
index('index','introEMOFCMOF','introEMOFCMOF','introUml2',unused).
index('index','mdsd','mdsd','introMdsd',unused).
index('index','oaw','oaw','mdsd',unused).
index('index','oawExample','oawExample','oaw',unused).
index('index','lexerBundle','lexerBundle','mdsd',unused).
index('index','fabbricaBundle','fabbricaBundle','lexerBundle',unused).
index('index','dslComm','dslComm','mdsd',unused).
index('index','piattaformaComm','piattaformaComm','dslComm',unused).
index('index','semanticaContact','semanticaContact','dslComm',unused).
index('index','agentWorld','Un mondo ad agenti','',unused).
index('index','agentiArchitetturaSocieta','agentiArchitetturaSocieta','agentWorld',unused).
index('index','agentiArchitetturaAmbiente','agentiArchitetturaAmbiente','agentWorld',unused).
index('index','aUMLIntro','aUMLIntro','agentWorld',unused).
index('index','f_aUMLProtocolli','aUMLProtocolli','aUMLIntro',unused).
index('index','aUMLProtocolliRuoliMultipli','aUMLProtocolliRuoliMultipli','aUMLIntro',unused).
index('index','aUMLProtocolliMessaggi','f_aUMLProtocolliMessaggi','aUMLIntro',unused).
index('index','aUMLProtocolliVincoli','aUMLProtocolliVincoli','aUMLIntro',unused).
index('index','aUMLProtocolliAlternativi','aUMLProtocolliAlternativi','aUMLIntro',unused).
index('index','aUMLProtocolliCombinati','aUMLProtocolliCombinati','aUMLIntro',unused).
index('index','aUMLLingComm','aUMLLingComm','aUMLIntro',unused).
index('index','bibliografia','Bibliografia','',unused).
index('index','mapProcess','Map: process','',unused).
index('index','mapModelling','Map: modelling','',unused).
index('index','mapWorkflow','Map: workflow','',unused).
index('index','mapProcessActivity','Map: mapProcessActivity','',unused).

% --------------------------------------------- 
% Dita files 
% --------------------------------------------- 
tocDitaMap('introduzione','content/book/introduzione/introduzione.dita',concept,none).

tocDitaMap('crisiSoftware','content/book/introduzione/crisiSoftware.dita',concept,'introduzione').

tocDitaMap('dimAlgoritmica','content/book/introduzione/dimAlgoritmica.dita',concept,'introduzione').

tocDitaMap('dimSistemistica','content/book/introduzione/dimSistemistica.dita',concept,'introduzione').

tocDitaMap('ingSoftware','content/book/ingSoft/ingSoftware.dita',concept,'introduzione').

tocDitaMap('metodoMetodologia','content/book/ingSoft/metodoMetodologia.dita',concept,'ingSoftware').

tocDitaMap('storiaDelleMetodologie','content/book/ingSoft/storiaDelleMetodologie.dita',concept,'ingSoftware').

tocDitaMap('cmm','content/book/ingSoft/cmm.dita',concept,'ingSoftware').

tocDitaMap('processiSviluppoSoftware','content/book/processi/processiSviluppoSoftware.dita',concept,none).

tocDitaMap('qualita','content/book/processi/qualita.dita',concept,'processiSviluppoSoftware').

tocDitaMap('processiACasscata','content/book/processi/processiACasscata.dita',concept,'processiSviluppoSoftware').

tocDitaMap('processiASpirale','content/book/processi/processiASpirale.dita',concept,'processiSviluppoSoftware').

tocDitaMap('processiBasatiSuModelli','content/book/processi/processiBasatiSuModelli.dita',concept,'processiSviluppoSoftware').

tocDitaMap('processiAgili','content/book/processi/processiAgili.dita',concept,'processiSviluppoSoftware').

tocDitaMap('xpPratiche','content/book/processi/xpPratiche.dita',concept,'processiAgili').

tocDitaMap('qualeProcesso','content/book/processi/qualeProcesso.dita',concept,'processiSviluppoSoftware').

tocDitaMap('versoUnProcesso','content/book/modelBased/versoUnProcesso.dita',concept,none).

tocDitaMap('paradigmi','content/book/paradigmi/paradigmi.dita',concept,'versoUnProcesso').

tocDitaMap('sintassiSemantica','content/book/paradigmi/sintassiSemantica.dita',concept,'paradigmi').

tocDitaMap('macchineBase','content/book/paradigmi/macchineBase.dita',concept,'paradigmi').

tocDitaMap('macchineAstratte','content/book/paradigmi/macchineAstratte.dita',concept,'macchineBase').

tocDitaMap('funzioniProcedure','content/book/paradigmi/funzioniProcedure.dita',concept,'paradigmi').

tocDitaMap('moduliOggetti','content/book/paradigmi/moduliOggetti.dita',concept,'paradigmi').

tocDitaMap('oggetti','content/book/paradigmi/oggetti.dita',concept,'paradigmi').

tocDitaMap('daOggettiAUML','content/book/paradigmi/daOggettiAUML.dita',concept,'paradigmi').

tocDitaMap('componentiSoftware','content/book/paradigmi/componentiSoftware.dita',concept,'paradigmi').

tocDitaMap('inversioneControllo','content/book/paradigmi/inversioneControllo.dita',concept,'componentiSoftware').

tocDitaMap('paradigmaAgenti','content/book/paradigmi/paradigmaAgenti.dita',concept,'paradigmi').

tocDitaMap('agenti','content/book/paradigmi/agenti.dita',concept,'paradigmaAgenti').

tocDitaMap('agentiVsOggetti','content/book/paradigmi/agentiVsOggetti.dita',concept,'paradigmaAgenti').

tocDitaMap('umlFirst','content/book/uml/umlFirst.dita',concept,'versoUnProcesso').

tocDitaMap('concettoDiModello','content/book/uml/concettoDiModello.dita',concept,'umlFirst').

tocDitaMap('introUml','content/book/uml/introUml.dita',concept,'umlFirst').

tocDitaMap('layerUml','content/book/uml/layerUml.dita',concept,'umlFirst').

tocDitaMap('introMOF','content/book/uml/introMOF.dita',concept,'umlFirst').

tocDitaMap('diagrammiAM','content/book/uml/diagrammi.dita',concept,'umlFirst').

tocDitaMap('introUMLProfili','content/book/uml/introUMLProfili.dita',concept,'umlFirst').

tocDitaMap('umlComeLinguaggio','content/book/uml/umlComeLinguaggio.dita',concept,'umlFirst').

tocDitaMap('introUMLAction','content/book/uml/introUMLAction.dita',concept,'umlFirst').

tocDitaMap('introOCL','content/book/ocl/introOCL.dita',concept,'umlFirst').

tocDitaMap('architettureSistemi','content/book/sistemi/architettureSistemi.dita',concept,'versoUnProcesso').

tocDitaMap('stileArchitetturale','content/book/sistemi/stileArchitetturale.dita',concept,'architettureSistemi').

tocDitaMap('mda','content/book/sistemi/mda.dita',concept,'architettureSistemi').

tocDitaMap('dimensioniSistemi','content/book/sistemi/dimensioniSistemi.dita',concept,'versoUnProcesso').

tocDitaMap('struttura','content/book/sistemi/struttura.dita',concept,'dimensioniSistemi').

tocDitaMap('interazione','content/book/sistemi/interazioneSistemi.dita',concept,'dimensioniSistemi').

tocDitaMap('comportamento','content/book/sistemi/comportamentoSistemi.dita',concept,'dimensioniSistemi').

tocDitaMap('strutturaIntro','content/book/uml/struttura/introduzione.dita',concept,'struttura').

tocDitaMap('classi','content/book/uml/struttura/classi.dita',concept,'strutturaIntro').

tocDitaMap('package','content/book/uml/struttura/package.dita',concept,'strutturaIntro').

tocDitaMap('strutComp','content/book/uml/struttura/strutturacomposita.dita',concept,'strutturaIntro').

tocDitaMap('componentiD','content/book/uml/struttura/componenti.dita',concept,'strutturaIntro').

tocDitaMap('deploymentD','content/book/uml/struttura/deployment.dita',concept,'strutturaIntro').

tocDitaMap('interazioneIntro','content/book/uml/interazione/interazione.dita',concept,'interazione').

tocDitaMap('sequenzaIntro','content/book/uml/interazione/diagrammaSequenza.dita',concept,'interazioneIntro').

tocDitaMap('messaggio','content/book/uml/interazione/messaggio.dita',concept,'sequenzaIntro').

tocDitaMap('combinedfragment','content/book/uml/interazione/combinedfragment.dita',concept,'sequenzaIntro').

tocDitaMap('esempiInterazione','content/book/uml/interazione/esempiInterazione.dita',concept,'sequenzaIntro').

tocDitaMap('sincroni','content/book/uml/interazione/sincroni.dita',concept,'esempiInterazione').

tocDitaMap('asincroni','content/book/uml/interazione/asincroni.dita',concept,'esempiInterazione').

tocDitaMap('conclusioni','content/book/uml/interazione/conclusioni.dita',concept,'interazioneIntro').

tocDitaMap('comportamentoIntro','content/book/uml/comportamento/introComportamento.dita',concept,'comportamento').

tocDitaMap('stato','content/book/uml/comportamento/diagrammaStato.dita',concept,'comportamentoIntro').

tocDitaMap('attivita','content/book/uml/comportamento/diagrammaAttivita.dita',concept,'comportamentoIntro').

tocDitaMap('introPattern','content/book/pattern/introPattern.dita',concept,'versoUnProcesso').

tocDitaMap('ruoloPattern','content/book/pattern/ruoloPattern.dita',concept,'introPattern').

tocDitaMap('insiemiDiPattern','content/book/pattern/insiemiDiPattern.dita',concept,'introPattern').

tocDitaMap('patternLanguages','content/book/pattern/patternLanguages.dita',concept,'introPattern').

tocDitaMap('piattaforme','content/book/piattaforme/piattaforme.dita',concept,'versoUnProcesso').

tocDitaMap('processoLogico','content/book/wkflow/processoLogico.dita',concept,none).

tocDitaMap('impostazioneGenerale','content/book/wkflow/impostazioneGenerale.dita',concept,'processoLogico').

tocDitaMap('sitoApplicazione','content/book/wkflow/sitoApplicazione.dita',concept,'processoLogico').

tocDitaMap('workflowRequisiti','content/book/modelBased/fasi/workflowRequisiti.dita',concept,'processoLogico').

tocDitaMap('ieeeRequisiti','content/book/modelBased/fasi/ieeeRequisiti.dita',concept,'workflowRequisiti').

tocDitaMap('analisiRequisiti','content/book/modelBased/fasi/analisiRequisiti.dita',concept,'workflowRequisiti').

tocDitaMap('useCase','content/book/modelBased/fasi/useCase.dita',concept,'analisiRequisiti').

tocDitaMap('relazioniUsecases','content/book/modelBased/fasi/relazioniUsecases.dita',concept,'useCase').

tocDitaMap('scenari','content/book/modelBased/fasi/scenari.dita',concept,'useCase').

tocDitaMap('requisitNonFunzionali','content/book/modelBased/fasi/requisitNonFunzionali.dita',concept,'workflowRequisiti').

tocDitaMap('workflowAnalisi','content/book/modelBased/fasi/workflowAnalisi.dita',concept,'processoLogico').

tocDitaMap('analisiProblema','content/book/modelBased/fasi/analisiProblema.dita',concept,'workflowAnalisi').

tocDitaMap('architetturaLogica','content/book/modelBased/fasi/architetturaLogica.dita',concept,'analisiProblema').

tocDitaMap('schemiArchitettura','content/book/modelBased/fasi/schemiArchitettura.dita',concept,'architetturaLogica').

tocDitaMap('layers','content/book/modelBased/fasi/layers.dita',concept,'analisiProblema').

tocDitaMap('analisiRischi','content/book/modelBased/fasi/analisiRischi.dita',concept,'workflowAnalisi').

tocDitaMap('pianoCollaudo','content/book/modelBased/fasi/pianoCollaudo.dita',concept,'processoLogico').

tocDitaMap('pianoLavoro','content/book/modelBased/fasi/pianoLavoro.dita',concept,'processoLogico').

tocDitaMap('workflowProgetto','content/book/modelBased/fasi/workflowProgetto.dita',concept,'processoLogico').

tocDitaMap('progettazione','content/book/modelBased/fasi/progettazione.dita',concept,'workflowProgetto').

tocDitaMap('sviluppoBottomUp','content/book/modelBased/fasi/sviluppoBottomUp.dita',concept,'workflowProgetto').

tocDitaMap('piattaformeFramework','content/book/modelBased/fasi/piattaformeFramework.dita',concept,'sviluppoBottomUp').

tocDitaMap('applicationFramework','content/book/modelBased/fasi/applicationFramework.dita',concept,'sviluppoBottomUp').

tocDitaMap('sviluppoTopDown','content/book/modelBased/fasi/sviluppoTopDown.dita',concept,'workflowProgetto').

tocDitaMap('projectByPattern','content/book/pattern/projectByPattern.dita',concept,'sviluppoTopDown').

tocDitaMap('implementazione','content/book/modelBased/fasi/implementazione.dita',concept,'processoLogico').

tocDitaMap('workflowCollaudo','content/book/modelBased/fasi/workflowCollaudo.dita',concept,'processoLogico').

tocDitaMap('deployment','content/book/modelBased/fasi/deployment.dita',concept,'processoLogico').

tocDitaMap('maintenance','content/book/modelBased/fasi/maintenance.dita',concept,'processoLogico').

tocDitaMap('esempioModelBased','content/lab/exp/esempioModelBased.dita',concept,none).

tocDitaMap('analisiRequisitiExp','content/lab/exp/analisiRequisitiExp.dita',concept,'esempioModelBased').

tocDitaMap('modelloDominioExp','content/lab/exp/modelloDominioExp.dita',concept,'analisiRequisitiExp').

tocDitaMap('modelloTokenExp','content/lab/exp/modelloTokenExp.dita',concept,'modelloDominioExp').

tocDitaMap('modelloExpExp','content/lab/exp/modelloExpExp.dita',concept,'modelloDominioExp').

tocDitaMap('pianoCollaudoExp','content/lab/exp/pianoCollaudoExp.dita',concept,'analisiRequisitiExp').

tocDitaMap('sintassiAstrattaExp','content/lab/exp/sintassiAstrattaExp.dita',concept,'analisiRequisitiExp').

tocDitaMap('genCodeToolsExp','content/lab/exp/genCodeToolsExp.dita',concept,'analisiRequisitiExp').

tocDitaMap('analisiProblemaExp','content/lab/exp/analisiProblemaExp.dita',concept,'esempioModelBased').

tocDitaMap('archLogicaExp','content/lab/exp/archLogicaExp.dita',concept,'analisiProblemaExp').

tocDitaMap('archLogicaStruttura','content/lab/exp/archLogicaStruttura.dita',concept,'archLogicaExp').

tocDitaMap('archLogicaInterazione','content/lab/exp/archLogicaInterazione.dita',concept,'archLogicaExp').

tocDitaMap('archLogicaComportamento','content/lab/exp/archLogicaComportamento.dita',concept,'archLogicaExp').

tocDitaMap('comportamentoSistema','content/lab/exp/comportamentoSistema.dita',concept,'archLogicaExp').

tocDitaMap('pianoLavoroExp','content/lab/exp/pianoLavoroExp.dita',concept,'esempioModelBased').

tocDitaMap('progettoExp','content/lab/exp/progettoExp.dita',concept,'esempioModelBased').

tocDitaMap('inputDev08Project','content/lab/exp/inputDev08Project.dita',concept,'progettoExp').

tocDitaMap('lexer08Project','content/lab/exp/lexer08Project.dita',concept,'progettoExp').

tocDitaMap('parser08Project','content/lab/exp/parser08Project.dita',concept,'progettoExp').

tocDitaMap('evaluator08Project','content/lab/exp/evaluator08Project.dita',concept,'progettoExp').

tocDitaMap('implementazioneExp','content/lab/exp/implementazioneExp.dita',concept,'esempioModelBased').

tocDitaMap('inputDevImplementation','content/lab/exp/inputDevImplementation.dita',concept,'implementazioneExp').

tocDitaMap('lexer08Implementation','content/lab/exp/lexer08Implementation.dita',concept,'implementazioneExp').

tocDitaMap('parser08Implementation','content/lab/exp/parser08Implementation.dita',concept,'implementazioneExp').

tocDitaMap('evaluatorImplementation','content/lab/exp/evaluatorImplementation.dita',concept,'implementazioneExp').

tocDitaMap('sysExpImplementation','content/lab/exp/sysExpImplementation.dita',concept,'implementazioneExp').

tocDitaMap('introTecnologie','content/book/tecno/introTecnologie.dita',concept,none).

tocDitaMap('componenti','content/book/tecno/componenti/componenti.dita',concept,'introTecnologie').

tocDitaMap('osgi','content/book/tecno/OSGi/osgi.dita',concept,'componenti').

tocDitaMap('bundle','content/book/tecno/OSGi/bundle.dita',concept,'osgi').

tocDitaMap('bundleDependency','content/book/tecno/OSGi/bundleDependency.dita',concept,'osgi').

tocDitaMap('classLoading','content/book/tecno/OSGi/classLoading.dita',concept,'osgi').

tocDitaMap('bundleLifeCycle','content/book/tecno/OSGi/bundleLifeCycle.dita',concept,'osgi').

tocDitaMap('bundleObject','content/book/tecno/OSGi/bundleObject.dita',concept,'osgi').

tocDitaMap('bundleContext','content/book/tecno/OSGi/bundleContext.dita',concept,'osgi').

tocDitaMap('osgiServices','content/book/tecno/OSGi/osgiServices.dita',concept,'osgi').

tocDitaMap('osgiServiceDependency','content/book/tecno/OSGi/osgiServiceDependency.dita',concept,'osgi').

tocDitaMap('osgiServiceTracker','content/book/tecno/OSGi/osgiServiceTracker.dita',concept,'osgi').

tocDitaMap('osgiServiceBinder','content/book/tecno/OSGi/osgiServiceBinder.dita',concept,'osgi').

tocDitaMap('equinoxUsageTutorial','content/book/tecno/OSGi/equinoxUsageTutorial.dita',concept,'osgi').

tocDitaMap('realizzareBundle','content/book/tecno/OSGi/realizzareBundle.dita',concept,'osgi').

tocDitaMap('introMdsd','content/book/modelDriven/introMdsd.dita',concept,none).

tocDitaMap('introUml2','content/book/uml211/introUml2.dita',concept,'introMdsd').

tocDitaMap('razionaleMOF','content/book/uml211/razionaleMOF.dita',concept,'introUml2').

tocDitaMap('riusoInMOF','content/book/uml211/riusoInMOF.dita',concept,'introUml2').

tocDitaMap('introEMOFCMOF','content/book/uml211/introEMOFCMOF.dita',concept,'introUml2').

tocDitaMap('mdsd','content/book/modelDriven/mdsd.dita',concept,'introMdsd').

tocDitaMap('oaw','content/book/modelDriven/oaw.dita',concept,'mdsd').

tocDitaMap('oawExample','content/book/modelDriven/oawExample.dita',concept,'oaw').

tocDitaMap('lexerBundle','content/lab/bundle/lexerBundle.dita',concept,'mdsd').

tocDitaMap('fabbricaBundle','content/lab/bundle/fabbricaBundle.dita',concept,'lexerBundle').

tocDitaMap('dslComm','content/book/modelDriven/dslComm.dita',concept,'mdsd').

tocDitaMap('piattaformaComm','content/book/modelDriven/piattaformaComm.dita',concept,'dslComm').

tocDitaMap('semanticaContact','content/book/modelDriven/semanticaContact.dita',concept,'dslComm').

tocDitaMap('agentWorld','content/book/agenti/agentWorld.dita',concept,none).

tocDitaMap('agentiArchitetturaSocieta','content/book/agenti/agentiArchitetturaSocieta.dita',concept,'agentWorld').

tocDitaMap('agentiArchitetturaAmbiente','content/book/agenti/agentiArchitetturaAmbiente.dita',concept,'agentWorld').

tocDitaMap('aUMLIntro','content/book/agenti/aUMLIntro.dita',concept,'agentWorld').

tocDitaMap('f_aUMLProtocolli','content/book/agenti/aUMLProtocolli.dita',concept,'aUMLIntro').

tocDitaMap('aUMLProtocolliRuoliMultipli','content/book/agenti/aUMLProtocolliRuoliMultipli.dita',concept,'aUMLIntro').

tocDitaMap('aUMLProtocolliMessaggi','content/book/agenti/aUMLProtocolliMessaggi.dita',concept,'aUMLIntro').

tocDitaMap('aUMLProtocolliVincoli','content/book/agenti/aUMLProtocolliVincoli.dita',concept,'aUMLIntro').

tocDitaMap('aUMLProtocolliAlternativi','content/book/agenti/aUMLProtocolliAlternativi.dita',concept,'aUMLIntro').

tocDitaMap('aUMLProtocolliCombinati','content/book/agenti/aUMLProtocolliCombinati.dita',concept,'aUMLIntro').

tocDitaMap('aUMLLingComm','content/book/agenti/aUMLLingComm.dita',concept,'aUMLIntro').

tocDitaMap('bibliografia','content/biblio/bibliografia.dita',concept,none).

tocDitaMap('mapProcess','content/book/maps/mapProcess.dita',concept,none).

tocDitaMap('mapModelling','content/book/maps/mapModelling.dita',concept,none).

tocDitaMap('mapWorkflow','content/book/maps/mapWorkflow.dita',concept,none).

tocDitaMap('mapProcessActivity','content/book/maps/mapProcessActivity.dita',concept,none).


% --------------------------------------------- 
% Relations
% --------------------------------------------- 


% -------------------------------------------------------------------
% ----------------------------------------------
% PLEASE DO NOT CHANGE THE RULES THAT FOLLOW
% ----------------------------------------------
% -------------------------------------------------------------------
item( 'Entry', 'Entry', 'LOTYPE3', 'support/Welcome.html').
item( 'Help', 'Help', 'LOTYPE3', 'support/Help.html').
%%%%%% item( ID,ID,'LOTYPE3',File):- tocDitaMap(ID,File,_,_).
% --------------------------------------------- 
% Package 
% --------------------------------------------- 
package('it.unibo.model').

% ----------------------------------------------
% General complementary rules for relations
% ----------------------------------------------
itemRelation( 'see',  ID1, ID2 ):- 
	itemRelation( 'more',  ID2, ID1 ).
itemRelation( 'lab',  ID1, ID2 ):- 
	itemRelation( 'exercise',  ID2, ID1 ).
itemRelation( 'more',  ID2, ID1 ):- 
	tocDitaMap(ID1,_,_,ID2).
	
% ----------------------------------------------
% Meta for the index and the user's itens
% ----------------------------------------------
meta('index', 'ADL SCORM', '1.2', educational, semanticDensity, 'very easy').

% ----------------------------------------------
% Meta default rule
% ----------------------------------------------
meta(ANY, 'ADL SCORM', '1.2', educational, semanticDensity, 'user'):-
%	println( text_term( ANY, user(_) ) ),
	text_term( ANY, user(_) ),!.
meta(ANY, 'ADL SCORM', '1.2', educational, semanticDensity, 'very easy').
   
% ----------------------------------------------
% CONTENTS (intensional, for the case: 
% one item-one file) TODO: try to remove
% ----------------------------------------------
itemContent( ID, File) :- item( ID,_,_,File).

% ----------------------------------------------
% FILES (intensional) TODO: try to remove
% ----------------------------------------------
file( FName ) :- 
	bagof( File, item( _,_,_,File), List ),
	member( FName, List ).
   
