/* Generated by AN DISI Unibo */ 
package it.unibo.resource1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Resource1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 var Count = 1  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name STARTS")
						CoapObserverSupport(myself, "localhost","8065","ctxresource1","resource1")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
				}	 
				state("handleUpdate") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitchGuarded({ Count < 3  
					}) )
					transition( edgeName="goto",targetState="endJob", cond=doswitchGuarded({! ( Count < 3  
					) }) )
				}	 
				state("work") { //this:State
					action { //it:State
						updateResourceRep( "$name : $Count"  
						)
						 
						 		   MsgUtil.outmagenta( "${name} (qakmodel) count= $Count" )		
						 		   Count = Count + 1   
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="handleUpdate",cond=whenDispatch("coapUpdate"))
				}	 
				state("endJob") { //this:State
					action { //it:State
						println("$name ENDS")
						 unibo.comm22.utils.CommUtils.waitTheUser("Type a key to exit");
								   System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
