/* Generated by AN DISI Unibo */ 
package it.unibo.ledqak22

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Ledqak22 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name STARTS")
					}
					 transition(edgeName="t00",targetState="handleThrill",cond=whenEvent("thrill"))
				}	 
				state("handleThrill") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("info(CMD)"), Term.createTerm("info(CMD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Cmd = payloadArg(0)  
								if(  Cmd=="on"  
								 ){ unibo.actor22comm.utils.ColorsOut.outappl( 
													"${name} - on", unibo.actor22comm.utils.ColorsOut.MAGENTA)
								}
								else
								 { unibo.actor22comm.utils.ColorsOut.outappl( 
								 					"${name} - off", unibo.actor22comm.utils.ColorsOut.GREEN)
								 }
						}
					}
					 transition(edgeName="t01",targetState="handleThrill",cond=whenEvent("thrill"))
				}	 
			}
		}
}
