/* Generated by AN DISI Unibo */ 
package it.unibo.pathcaller

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Pathcaller ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="doPath", cond=doswitch() )
				}	 
				state("doPath") { //this:State
					action { //it:State
						 val PathTodo =  "wwlwlwwlwl"   
						println("doexplore starts $PathTodo")
						request("dopath", "dopath($PathTodo,pathcaller)" ,"pathexec" )  
					}
					 transition(edgeName="t06",targetState="end",cond=whenReply("dopathdone"))
					transition(edgeName="t07",targetState="handelPathFailure",cond=whenReply("dopathfail"))
				}	 
				state("handelPathFailure") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						emit("alarm", "alarm(obstacle)" ) 
					}
				}	 
				state("end") { //this:State
					action { //it:State
						println("BYE")
					}
				}	 
			}
		}
}
